### ISSUE TITLE
Struggling to setup the local host that I run the monitor UI on as a server?

### ISSUE THREAD

**Issue by LawMixer** [mbecker20/monitor#12]
Right now, I'm trying to migrate from [Pterodactyl](https://pterodactyl.io/) and I couldn't see anything that you can host your containers in the same machine as the monitor UI - not unless I'm missing something.

I think it would be a good suggestion as if there was built-in templates for servers (like your own) or documentating how too for people like me, haha.

**Comment by mbecker20** [comment]
Hi, the difference here is that Monitor Core does not connect to your system directly, it must go through a periphery agent. See [https://docs.monitor.mogh.tech/docs/intro#architecture-and-components](https://docs.monitor.mogh.tech/docs/intro#architecture-and-components).

So in addition to running the Core docker container, also install the periphery agent, and then you can add your local server. See [https://docs.monitor.mogh.tech/docs/connecting-servers](https://docs.monitor.mogh.tech/docs/connecting-servers).

Let me know if anything is still unclear, or you have any ideas to improve the documentation.

**Comment by LawMixer** [comment]
I think the documentation on how to setup connecting servers, need to be more clear. 

For me, I have the periphery agent and it's running, but what do I put as my servers in the server tab?

**Comment by LawMixer** [comment]
After some digging, I found it out ``http://ip-here:8120``,  could use something in the documentation saying that.

**Comment by mbecker20** [comment]
I improved the server setup with more placeholders to guide the user. Sorry it wasn't so clear. I do have it in the docs, the second page of "connecting servers". [https://docs.monitor.mogh.tech/docs/connecting-servers/add-server](https://docs.monitor.mogh.tech/docs/connecting-servers/add-server)

**Comment by LawMixer** [comment]
Thank you, so far I love it! I will have to open up another issue for GitHub tokens being in the dashboard settings instead of that, and maybe GitHub Actions or something.

**Comment by mbecker20** [comment]
@LawMixer I will also include git / registry provider management in the UI in the next release. It will still support config file definition for those who prefer to do it that way.

**Comment by LawMixer** [comment]
Let's go, thank you! Amazing project!
