### ISSUE TITLE
[UI/UX] Parameter Entry UI Elements not easily visible

### ISSUE THREAD

**Issue by arcoast** [mbecker20/monitor#13]
Got this installed today and playing around, liking it so far but not made any significant progress yet! 

Got stumped by not being able to see the text entry boxes in dark mode.  They're visible but very subtle and I only realised when I changed it to light mode where I was meant to be entering parameters.

![image](https://github.com/user-attachments/assets/a637e511-2b20-46f8-884b-8e56cfd23426)

Still subtle in light mode, but more visible to my eye.

![image](https://github.com/user-attachments/assets/39cee62c-79d4-4c2f-8656-a90bd8d4af6f)

**Comment by mbecker20** [comment]
Good point. It hurts accessibility. I'll adjust the theme contrast

**Comment by mbecker20** [comment]
Another issue is the lack of input placeholders, I'll make sure all config has relevant placeholders to guide the usage.

**Comment by arcoast** [comment]
> Good point. It hurts accessibility. I'll adjust the theme contrast

Yeah, I'm not a young man anymore and my eyes aren't what they were!

**Comment by mbecker20** [comment]
Hi, how do you feel about the contrast in the latest releases? We did tweak it up, admittedly slightly, but also made sure to assign all inputs placeholders which helps them stand out as well.

<img width="931" alt="Screenshot 2024-08-15 at 5 32 44 PM" src="https://github.com/user-attachments/assets/7dfd1e0f-7175-442e-87e6-db70b603ee2b">

**Comment by arcoast** [comment]
@mbecker20 Yeah, that's much better in my opinion, I can clearly see the elements now.  Thank you so much!

(Sorry about the delay, been away on vacation)

I haven't closed the issue as it's your project so I will leave it to you just in case you want to do anything else, but as far as I'm concerned, my issue has been addressed.

Once again, thank you!
