### ISSUE TITLE
[Feature]: Expand GitHub support from dashboard instead of OAuth

### ISSUE THREAD

**Issue by LawMixer** [mbecker20/monitor#14]
In the settings page, maybe add a "Connections" and that could be for like GitHub tokens or applications depending on what you would like to do. An example would be like deployment to your application and then it could be posted on Discord via a webhook.

**Comment by mbecker20** [comment]
Your example sounds close to the Alerter resource type. It currently supports Slack but set up to expand to many more providers. I think discord is an obvious one for next.

As for native integrations accessible via UI, it's a great feature but can be difficult, I'm still focussed on building the core platform and maybe the community can help for the integrations.

**Comment by LawMixer** [comment]
All good! This website is amazing!

Yeah, configuring github tokens with the config files tend to be confusing.

I'm trying to figure out how to use a GitHub token to pull my repos and all, but I'm not sure. 

#For the alerts, sounds perfect! I might need to do some extra configuration for ports because I can't do python -port 5000:5000 but I'll hopefully find a way!

**Comment by mbecker20** [comment]
For the Github token, refer to their docs to create one: [https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-personal-access-token-classic](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-personal-access-token-classic).

Then you add a block like this to the [config file](https://github.com/mbecker20/monitor/blob/main/config_example/core.config.example.toml):

```
[[git_provider]]
domain = "github.com"
accounts = [
	{ username = "your_username", token = "your_token" },
]
```
Just input your actual username, and paste the token you made on Github following that first link.
