### ISSUE TITLE
feature: Being able to pick which deployment type you want (GitHub Repo, Docker Image, Compose, or etc)

### ISSUE THREAD

**Issue by LawMixer** [mbecker20/monitor#18]
Right now, it stands that the application doesn't know which one you want to do, which means if you are only pulling from a GitHub Repo, it will ask you for a builder and an image which really isn't good. 

This example is me pulling a GitHub repo and it won't let me pass by without Docker configurations:
https://i.imgur.com/jvjNTOE.png
https://i.imgur.com/uFaRQzl.png

**Comment by mbecker20** [comment]
Hi, Monitor has different Resource types, see [here](https://docs.monitor.mogh.tech/docs/resources).

In the screenshot, you have created a "Build", which the only purpose is to build a versioned docker image from the source you provide.

For Builds, you don't need to specify the Image Registry if you only need the image locally, just leave it as None. Deploying images that are built on the deployment server is not a production level solution, however Monitor supports this. 

1. Make a "Builder" pointing to the server you want to deploy on.
2. Make a "Build" pointing to the Builder you made, and the repo you want to deploy
3. Make a "Deployment" on the server you want to deploy on, and attach the build. Configure the container settings, and check the setting for "redeploy on build"
4. Build the build, then you can deploy it. Note all actions (including build) will be available from the Deployment page.

Let me know if this accomplishes what you want to do.

**Comment by mbecker20** [comment]
Also, its very easy to deploy Gitea. You can use this as the docker registry, then you can build on a different server (like spawn AWS instances for each build, not expensive). This way, the server running the service won't experience impact if the build uses a lot of resources.

**Comment by mbecker20** [comment]
The Stack resource, which will be included in v1.13, will also be able to clone a repo with source code on target server, and `docker compose up --build` if you wish. This option is all in one. I think i will be able to release this week.

<img width="1251" alt="Screenshot 2024-08-04 at 2 38 57 PM" src="https://github.com/user-attachments/assets/a0fa190b-3cae-442b-aa0a-ed2f11d6a341">
<img width="1216" alt="Screenshot 2024-08-04 at 2 39 21 PM" src="https://github.com/user-attachments/assets/26ff1c0d-5b95-4c39-aca2-a25043a043df">

**Comment by LawMixer** [comment]
Man, this is more confusing...let me figure this out.

Each build is giving this error whenever I don't have a Dockerfile in my repo:
https://i.imgur.com/CDPeb9B.png

**Comment by mbecker20** [comment]
For now, Builds only support creating docker images from a Dockerfile. It makes sense why it would fail here. You can read more about how things work in the build docs here: [https://docs.monitor.mogh.tech/docs/build-images](https://docs.monitor.mogh.tech/docs/build-images)

**Comment by LawMixer** [comment]
But..I just want to deploy my GitHub repo and my docker image is set to none, I'm not sure why it's telling me that it's not there whenever it's None:

https://i.imgur.com/kKiHRzi.png

**Comment by mbecker20** [comment]
Maybe you can tell me a bit more about what you wish to do? Maybe the Repo resource will fit your use better, since you don't need to build a docker image?

**Comment by mbecker20** [comment]
Also, it will help me to know your experience level using Docker, as using Monitor is mainly coming from how Docker works.

**Comment by LawMixer** [comment]
Oh, I'm sorry for the confusing. Right now, all I'm trying to do is clone my private repo from GitHub and then run it with ``python -u start file``.

I don't have a dockerfile in this repo, and don't wish to use dockerfiles for this project - though I do have this for other projects.

**Comment by LawMixer** [comment]
I was hoping that I could just deploy straight from Repos section, and just configure my start files and all - doesn't seem to be the case, maybe I'm missing something?

**Comment by mbecker20** [comment]
Monitor will support this, using the Repo resource. But it is barebones:

1. Make a script in the repo to do what needs to be done to build and start the project with a process manager on the system like systemd (it has to run unnattended). 
2. Then you set Monitor to run this script every time the Repo is pulled by configuring On Pull command on the Repo
3. You can log into the server with SSH and view the process logs using the process manager you chose

Monitor can't help any more than this for non-Docker deployments. But to be honest, your use can sound perfect to Dockerize, you can follow instructions here: [https://www.docker.com/blog/how-to-dockerize-your-python-applications/](https://www.docker.com/blog/how-to-dockerize-your-python-applications/). If you just tell Monitor how to build the image with a Dockerfile in the repo (just one file), you can follow the process I described above, and use Monitor to also see the process status and logs.

Hope this helps.

**Comment by LawMixer** [comment]
> Make a script in the repo to do what needs to be done to build and start the project with a process manager on the system like systemd (it has to run unnattended).
Then you set Monitor to run this script every time the Repo is pulled by configuring On Pull command on the Repo

This sounds right, but the only thing that stops me from going forward is it requires a docker file which would be hard for me to do.

**Comment by mbecker20** [comment]
The Repo resource does not require dockerfile

**Comment by LawMixer** [comment]
I think I will just do a dockerfile - I think I'm just going to run in the same deadends I'm running in. Thanks for your help!

**Comment by mbecker20** [comment]
Sure, let me know if you run into anything else. I'm sorry I don't have the resources to provide more guides but that will also improve with time.

**Comment by LawMixer** [comment]
Thank you - Git wouldn't allow me to commit my changes, so it wouldn't push the new dockerfile that I added...haha my bad!

What's the best way to move files over (redis, mongodb, etc) over to using monitor? Is there any built-in way that I could use? Right now, it's currently on a seperate docker network, and still running.

**Comment by mbecker20** [comment]
Periphery can pick up any containers on the host it is installed on. The network won't be an issue. To add existing containers to Monitor, you can make a deployment with the same name as the container, and set it to be on the same server as where the container is running.

Then you should see the container being picked up at this point. You will see the status, Start/stop container, and be able to view to logs. 

Monitor is not currently able to import what the Deployment configuration should be from an existing container, so you have to configure things like the images, volumes, extra args that are necessary to "Redeploy" the container. Don't forget this, or it won't work to "Redeploy".

**Comment by LawMixer** [comment]
> Monitor is not currently able to import what the Deployment configuration should be from an existing container, so you have to configure things like the image name, network, ports, volumes, environment that is necessary to "Redeploy" the container. Don't forget this, or it won't work to "Redeploy".

I will wait for the import deployment configuration from an existing container to come out to avoid any issues with me manually doing it - that would probably save me a bunch of time and effort trying to do this all over again..Thank you!

**Comment by mbecker20** [comment]
Unfortunately, it would be substantial to import the config for running containers, I don't plan support for this. Just too many edge cases for different users, will just lead to problems. 

Recommend you explore a declarative approach to what you run, though. You should already have it stored somewhere how they are configured? If you set those fields on deployment, it will work.

**Comment by LawMixer** [comment]
> Unfortunately, it would be substantial to import the config for running containers to be able to redeploy them, I don't plan support for this any time soon. Just too many edge cases for different users, will just lead to problems.
> 
> Recommend you explore a declarative approach to what you run, though. You should already have it stored somewhere how your services are configured? If you set those fields on deployment, it will work. And going forward for you, Monitor will store how everything should be configured in one place.

Yeah, I could stop my container and then redeploy it with monitor using the same container name, but wouldn't it not have the same configuration or will it keep the same configuration?

**Comment by mbecker20** [comment]
You can stop/ start the container with Monitor, but redeploy will recreate the container with the config you give to Monitor.

**Comment by LawMixer** [comment]
It's on a different network - how would I tell Monitor to use the old configuration or will it stay the same if it's the same container?

**Comment by mbecker20** [comment]
The container config will stay the same if its just starting / stopping the same container.

**Comment by mbecker20** [comment]
Re using `docker inspect`, yes this is the method I considered and it would be really nice to have, however consider it to be outside the Core of what Monitor intends to do well, because I don't know a way to do it without bad edge cases. This makes it more of a liability, and can hurt user trust if they use this import, and on redeploy it breaks their setup. I would rather not provide the feature, and leave it to them to configure how Monitor should deploy.

This is what I mean when I say before:
```
Unfortunately, it would be substantial to import the config for running containers to be able to redeploy them, I don't plan support for this any time soon. Just too many edge cases for different users, will just lead to problems.
```
