### ISSUE TITLE
feature: Ablity to put a secret in GitHub webhook to make it more secure

### ISSUE THREAD

**Issue by LawMixer** [mbecker20/monitor#22]
Being able to put a secret in GitHub webhook, so nobody can just make a request and then it won't be checked is kind of a safety and security hazard.

Example on GitHub:
https://i.imgur.com/aXm3yo4.png

**Comment by mbecker20** [comment]
Hi, you can configure what to put here using the config file field `webhook_secret`. You can also use environment variable MONITOR_WEBHOOK_SECRET to pass it to core. See [https://github.com/mbecker20/monitor/blob/59cb86d5990ffc4e8959624122c4a8bed6d74352/config_example/core.config.example.toml#L20](https://github.com/mbecker20/monitor/blob/59cb86d5990ffc4e8959624122c4a8bed6d74352/config_example/core.config.example.toml#L20).

Then you just put the same value in this field on Github side (or Gitea side, whichever git provider).

Monitor will perform validation using HMAC SHA256 signature check following their procedure here: [https://docs.github.com/en/webhooks/using-webhooks/validating-webhook-deliveries#validating-webhook-deliveries](https://docs.github.com/en/webhooks/using-webhooks/validating-webhook-deliveries#validating-webhook-deliveries)
Monitor code: [https://github.com/mbecker20/monitor/blob/59cb86d5990ffc4e8959624122c4a8bed6d74352/bin/core/src/listener/github/mod.rs#L161](https://github.com/mbecker20/monitor/blob/59cb86d5990ffc4e8959624122c4a8bed6d74352/bin/core/src/listener/github/mod.rs#L161)

**Comment by LawMixer** [comment]
Oh - Could we have this in-app instead of in the configure file and the ability to change secrets per build?

**Comment by mbecker20** [comment]
It can be done, its not super high priority to me to change the secret per-build / repo / stack IMO. You can configure this on an Environment variable (MONITOR_WEBHOOK_SECRET) on core container too, don't need config file.

**Comment by LawMixer** [comment]
Most of my projects are under organizations, which I like to seperate my secrets to my organization just a preference.

**Comment by mbecker20** [comment]
Hey, I did it in this commit: [https://github.com/mbecker20/monitor/commit/8d75fa3f2f17aeba9cba63d31201bd61607fd2b3](https://github.com/mbecker20/monitor/commit/8d75fa3f2f17aeba9cba63d31201bd61607fd2b3)

![Screenshot 2024-08-11 at 10 20 51 PM](https://github.com/user-attachments/assets/e7e6e612-b967-4c66-9c98-01b45814c37a)

Just use the latest build.
