### ISSUE TITLE
1.13 aarch64 image not actually aarch64

### ISSUE THREAD

**Issue by C0untZero** [mbecker20/monitor#25]
Hey again!
I was very happy when I saw that 1.13 Komodo was released, can't wait to try the compose stacks :)

Just one minor hitch - it seems that the aarch64 package wasn't built correctly - can't seem to run it on my RPi, I'm getting the same message as before again:
`The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested `

Thanks for your help!

**Comment by C0untZero** [comment]
I've tried with the following images: 1.13.8-aarch64, 1.13.9-aarch64, and 1.13.10-aarch64.
Same behavior for all three, didn't make sense to go further back.

**Comment by mbecker20** [comment]
Sorry you tried all those! You are right, I mixed up the instance type and built it on another x86. Ill send 1.13.11, will be about 20 mins

**Comment by C0untZero** [comment]
Don't be sorry, I don't mind testing os stuff I use. Glad I could find the problem so someone else doesn't have to. Thanks for the quick response.

**Comment by mbecker20** [comment]
OK its done, try Core 1.13.11 and re-run periphery install here [https://github.com/mbecker20/monitor/tree/main/scripts](https://github.com/mbecker20/monitor/tree/main/scripts). It definitely is an ARM server this time :)

<img width="1189" alt="Screenshot 2024-08-11 at 11 34 37 AM" src="https://github.com/user-attachments/assets/d696a955-77c6-4ece-87f6-858f3ab11e5e">

**Comment by C0untZero** [comment]
That did it.
Thanks again!

**Comment by mbecker20** [comment]
Hey, would you try this one? ghcr.io/mbecker20/monitor:latest-aarch64-c7g

Its built on AWS graviton arm based chipset, vs whatever Hetzner uses. It runs fine on the hetzner arm box. Just want to double check it with you if you're willing

**Comment by C0untZero** [comment]
Yup, that one works as well.

**Comment by mbecker20** [comment]
Awesome thanks. Build setup should be solid now using AWS instead of Hetzner

**Comment by C0untZero** [comment]
No problem, feel free to @ me any time you need a hand :)
Just confirmed stack deployment works, so now just need to bite the bullet and migrate all my stacks from omv compose to monitor 😅

**Comment by C0untZero** [comment]
Will the c7g tag stay, or will it revert to aarch64 for future releases?

**Comment by mbecker20** [comment]
The c7g tag was just a test tag for the change in instance type. Future images will be built with the c7g instance but go back to just ghcr.io/mbecker20/monitor:latest-aarch64

**Comment by mbecker20** [comment]
Let me know if you'd like any help. I am about to push out a few fixes for edge cases I noticed from deploying more compose files on the demo. Will just be 1.13.1 patch release in place.

**Comment by C0untZero** [comment]
Hopefully I won't need it, thanks for the offer!
