### ISSUE TITLE
feature: webhook support gitea

### ISSUE THREAD

**Issue by Lukas-Heiligenbrunner** [mbecker20/monitor#30]
I tried to setup the webook with Gitea. I'm sending the webook with POST to the url provided in stack settings:
http://192.168.0.78:9120/listener/github/stack/66bb5edcfa9aae4c152233d8/deploy
But there seems to fail a signature verification:
`2024-08-13T14:44:58.840775Z  WARN stack_pull_webhook{id="66bb5edcfa9aae4c152233d8"}: core::listener::github: failed to run stack pull webook for stack 66bb5edcfa9aae4c152233d8 | no signature in headers`

Here is the code part:
https://github.com/mbecker20/monitor/blob/2d0c1724db77f8b1211dd60436f015ee1000be89/bin/core/src/listener/github/mod.rs#L226

A possible solution might be to disable this check via an env var? 

Great project btw. thanks a lot!

**Comment by mbecker20** [comment]
Hey, Gitea webhooks definitely works. It looks like you forgot to put the secret though. It should match the one you pass in the Environment [here].(https://github.com/mbecker20/monitor/blob/2d0c1724db77f8b1211dd60436f015ee1000be89/config_example/core.compose.yaml#L23)

**Comment by Lukas-Heiligenbrunner** [comment]
Ah, yes sorry my fault!
Maybe, if i find some time I'll add some things to your docs :)
