### ISSUE TITLE
bug: deleting sync doesn't clear its alert

### ISSUE THREAD

**Issue by C0untZero** [mbecker20/monitor#32]
![image](https://github.com/user-attachments/assets/85931acb-ff58-46a2-87fd-626f7cec4cf5)
If you create a sync which gets pending updates but you don't update and delete the sync instead, the alert remains.

**Comment by mbecker20** [comment]
Great catch!! Fix out in a few.

**Comment by mbecker20** [comment]
Fixed in this commit: [https://github.com/mbecker20/monitor/commit/a89bd4a36d97be469a59faf975e0381101bda936](https://github.com/mbecker20/monitor/commit/a89bd4a36d97be469a59faf975e0381101bda936)

**Comment by C0untZero** [comment]
Confirmed fix, the alert is gone! Thanks!
