### ISSUE TITLE
Red "2" doesn't go away if the warning is fixed within the system resources

### ISSUE THREAD

**Issue by LawMixer** [mbecker20/monitor#38]
The red "2" indicates that the server was maxed out on resources, or something is wrong, and my server reached 100% - it was my mistake and I fixed the mistake (was a process that was killing it). 

It has yet to go away,  and I've tried these solutions:
- Restarted my server, and the docker container; 
- Pulled the latest image changes to monitor (was on latest but was confirming); 

Let me know if you need anymore information.

**Comment by mbecker20** [comment]
Does the server stats page report the correct system usage? this page
<img width="1215" alt="Screenshot 2024-08-19 at 7 44 47 PM" src="https://github.com/user-attachments/assets/55b0b4e7-45c6-4379-9507-200edee3b5fd">

**Comment by LawMixer** [comment]
Looks like I didn't fix it, and looks like it was my hosting provider issue that resources aren't showing 1:1, gotta trust monitor more! haha..Thank you for doing this stats page, never knew it existed. I would love if it was implemented in the dashboard, or like customizable.

**Comment by mbecker20** [comment]
Yes, I know, this server stats page is too hidden! Integration directly to the dashboard is a good idea, and probably made it clearer to you what was going on.

FYI, I often jump to [https://www.netdata.cloud](https://www.netdata.cloud) for enterprise level monitoring and the self hosted option is pretty good. To see a _really_ good system stats dashboard, you can check out their [demo](https://app.netdata.cloud/spaces/netdata-demo/rooms/all-nodes/overview#metrics_correlation=false&after=-900&before=0&utc=America%2FNew_York&offset=-4&timezoneName=Eastern%20Time%20(US%20&modal=&modalTab=&modalParams=&selectedIntegrationCategory=deploy.operating-systems&force_play=false&d8a4e0c5-7c79-4145-900e-83a9f06fcb6a--chartName-val=menu_System-0).

I'm not sure Monitor will ever reach this height of system stats dashboard UI, at this stage of course it cannot compete with a dedicated tool for system stats UI with years of development. In contrast, Monitor is actually intended as a "first notice" to get an idea that there _is_ a problem, so users know to check out their comprehensive system stats dashboard like Netdata. That is why the Alerting features are prioritized -- See alert in Monitor topbar, check stats dashboard. Or see alert in Slack (Discord coming soon) and check stats dashboard.

If Monitor becomes really big I'm sure we can develop an amazing system stats dashboard on this platform.

Anyways I'll go ahead and close this issue.
