### ISSUE TITLE
arm64 images

### ISSUE THREAD

**Issue by C0untZero** [mbecker20/monitor#9]
Any plans on adding arm64 support/images?

Looks like a great project, was just about to spin it up on my RPi5, but alas, no arm image available.

**Comment by slient2010** [comment]
I think maybe you can compile the code for your platform.

**Comment by mbecker20** [comment]
Did you try running the image and it fails? I will definitely like to support ARM but haven't worked with it myself, just need a bit to see what changes are necessary.

**Comment by C0untZero** [comment]
> Did you try running the image and it fails? I will definitely like to support ARM but haven't worked with it myself, just need a bit to see what changes are necessary.

Yeah, I get the following:
![image](https://github.com/user-attachments/assets/d0e43ca2-6fd0-4faf-bf16-10d61a1987a4)
![image](https://github.com/user-attachments/assets/08056e28-5ac8-4cfc-84c4-728040c5e58f)



> I think maybe you can compile the code for your platform.

Could be, never done it though and would require some research on my part.

**Comment by C0untZero** [comment]
Welp, I just spent an hour trying to build this on my RPi, with no luck.
Note I don't have experience with building rust/typescript.
I've tried using the included vscode workspace and its tasks.json, but can't seem to complete a full client and frontend build to provide for the docker build of Dockerfile in ./bin/core.

@mbecker20 if you don't have an arm device yourself, I'd suggest setting up a github actions build workflow that could be pointed at an arm virtual env. I'd be willing to help with that if you want.
Alternatively if you could walk me through the build process on my RPi that could also produce an initial arm image.

**Comment by mbecker20** [comment]
Rpi will likely take forever to compile. Monitor supports spawning AWS ec2 instances for building, I can make an builder which spawns an ARM instance type to build it. And maybe Hetzner to test with.

**Comment by C0untZero** [comment]
That does sound more efficient, yeah. I'll leave you to it then, thanks for your effort. If there's anything I can help with let me know!

**Comment by mbecker20** [comment]
Try this for core: [https://github.com/mbecker20/monitor/pkgs/container/monitor_core_aarch64](https://github.com/mbecker20/monitor/pkgs/container/monitor_core_aarch64). I also added a `periphery-aarch64` binary to the [release](https://github.com/mbecker20/monitor/releases/tag/v1.12.0).

I updated the [periphery installer](https://github.com/mbecker20/monitor/tree/main/scripts) to try to detect arm and use the aarch64 binary if thats detected, it works on this hetzner arm box, maybe see if it works on Rpi?

**Comment by C0untZero** [comment]
That did it - the image ran.
However once started all I get of the web interface is a page with this:
![image](https://github.com/user-attachments/assets/e181cf1d-b660-469d-91fb-cf4cd63f185b)
Nothing on the page is clickable. No errors in the container logs.
Could this be a misconfiguration on my end?

**Comment by C0untZero** [comment]
Ah, local_auth is false by default, it seems to be working now! 
I'll have to try adding an arm periphery later, but thanks a lot for the arm image :)

**Comment by C0untZero** [comment]
I'll reopen and leave a comment once I test an arm periphery setup.

**Comment by mbecker20** [comment]
Awesome thanks

**Comment by mbecker20** [comment]
![Screenshot 2024-07-31 at 12 56 05 PM](https://github.com/user-attachments/assets/74fa54f4-9c93-4d53-934a-a74cbffe03be)

**Comment by C0untZero** [comment]
arm periphery also worked like a charm! thanks!

So this is a monitor instance with an RPi5 hosting the core and a periphery instance, and another RPi4 as just a periphery.
Does this make sense btw, is this intended use? ie having a periphery instance where core is?

![image](https://github.com/user-attachments/assets/58294d4d-8a3b-442c-9c39-e55bf5395165)

**Comment by C0untZero** [comment]
No problem, glad to help, thanks for sharing the project. Im looking forward to when you include docker compose, ill most likely fully migrate to monitor from omv compose. If you ever need an rpi test bed feel free to msg me.
